# Light Owl
set -g @thm_bg "#FBFBFB"
set -g @thm_fg "#403f53"
set -g @thm_status_bg "#FFFFFF"
set -g @thm_blue "#4876d6"
set -g @thm_red "#E64D49"
set -g @thm_overlay_0 "#93A1A1"
set -g @thm_overlay_1 "#5f7e97"

set -g pane-border-style "fg=#{@thm_overlay_0},bg=#{@thm_bg}"
set -g pane-active-border-style "fg=#{@thm_overlay_1},bg=#{@thm_bg}"

set -g status-right-length 250
set -g status-right ""

set -g status-position bottom
set -g status-style "bg=#{@thm_status_bg},fg=#{@thm_fg}"
set -g status-justify "absolute-centre"

set -wg automatic-rename on
set -g automatic-rename-format "#{pane_current_command}"

set -g window-status-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-style "bg=#{@thm_status_bg},fg=#{@thm_overlay_0}"
set -g window-status-last-style "bg=#{@thm_status_bg},fg=#{@thm_overlay_1}"

set -g window-status-activity-style "bg=#{@thm_red},fg=#{@thm_status_bg},bold"
set -g window-status-bell-style "bg=#{@thm_red},fg=#{@thm_status_bg},bold"
set -gF window-status-separator "#[bg=#{@thm_status_bg},fg=#{@thm_overlay_0}]│"

set -g window-status-current-format " #I#{?#{!=:#{window_name},Window},: #W,} "
set -g window-status-current-style "bg=#{@thm_blue},fg=#{@thm_status_bg},bold"
